namespace DZDDashboard.Data.Entities;

public class User : IAuditableEntity
{
    public int Id { get; set; }
    public string? Email { get; set; } 
    public string? NormalizedEmail { get; set; }
    public string? EntraObjectId { get; set; } 
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public UserGroup? UserGroup { get; set; }
    public int? UserGroupId { get; set; }
    public string? CompanyName { get; set; } 
    public Job? Job { get; set; } 
    public int? JobId { get; set; }
    public int? Grade { get; set; } 
    public Department? Department { get; set; } 
    public int? DepartmentId { get; set; }
    public Team? Team { get; set; } 
    public int? TeamId { get; set; }
    public DateTime? PositionStartDate { get; set; } 
    public DateTime? UserStartDate { get; set; } 
    public string? ContractType { get; set; } 
    public DateTime? ContractEndDate { get; set; } 
    public string? WorkModel { get; set; } 
    public PayrollLocation? PayrollLocation { get; set; } 
    public int? PayrollLocationId { get; set; }
    public int? AvatarId { get; set; } 
    public UserAvatar? Avatar { get; set; } 
    public User? ReportsTo { get; set; } 
    public int? ReportsToId { get; set; }
    public virtual ICollection<User> Subordinates { get; set; } = new List<User>();
    public int? OrganizationPositionId { get; set; }
    public OrganizationPosition? OrganizationPosition { get; set; }
    public string? ApprovalProcessUnit { get; set; } 
    public string? PhoneNumber { get; set; } 
    public string? PersonalEmail { get; set; } 
    public string? PersonalPhoneNumber { get; set; } 
    public DateTime? DateOfBirth { get; set; } 
    public string? Gender { get; set; } 
    public bool DisabilityStatus { get; set; } = false; 
    public string? DisabilityDegree { get; set; } 
    public string? Nationality { get; set; } 
    public string? CitizenshipNumber { get; set; } 
    public string? EducationStatus { get; set; } 
    public string? HighestEducationLevel { get; set; } 
    public string? HighSchoolName { get; set; } 
    public string? AssociateDegreeUniversityName { get; set; } 
    public string? AssociateDegreeProgramName { get; set; } 
    public string? BachelorsUniversityName { get; set; } 
    public string? BachelorsProgramName { get; set; } 
    public DateTime? BachelorsGraduatedDate { get; set; }
    public string? MastersUniversityName { get; set; } 
    public string? MastersProgramName { get; set; }
    public DateTime? MastersGraduatedDate { get; set; }
    public string? DoctorateUniversityName { get; set; } 
    public string? DoctorateProgramName { get; set; } 
    public string? DoctoratePhdStatus { get; set; } 
    public string? EmergencyContactFullName { get; set; } 
    public string? EmergencyContactRelationship { get; set; } 
    public string? EmergencyContactPhoneNumber { get; set; } 
    public string? MaritalStatus { get; set; } 
    public string? SpouseFullName { get; set; } 
    public List<ChildInfo>? Children { get; set; } 
    public string? LegalAddress { get; set; } 
    public string? CurrentAddress { get; set; } 
    public string? City { get; set; } 
    public string? Country { get; set; } 
    public string? BankName { get; set; } 
    public string? Iban { get; set; }
    public List<SalaryHistory>? SalaryHistories { get; set; } 
    public string? RegistrationNumber { get; set; } 
    public List<GradeHistory>? GradeHistories { get; set; } 
    public DateTime? PositionUpdateDate { get; set; } 
    public string? CvFilePath { get; set; } 
    public string? AutoEnrollmentPensionStatus { get; set; } 
    public DateTime? EmployerPensionStartDate { get; set; } 
    public bool HasEmployerPension { get; set; } 
    public decimal? EmployerPensionEmployeeContribution { get; set; } 
    public decimal? EmployerPensionEmployerContribution { get; set; }
    public bool HasPrivateHealthInsurance { get; set; } 
    public decimal? PrivateHealthInsuranceEmployeeCost { get; set; }
    public decimal? PrivateHealthInsuranceDependentCost { get; set; }
    public decimal? MealBenefitAmount { get; set; }
    public string? UnitName { get; set; }
    public List<UserTraining>? UserTrainings { get; set; }
    public List<TargetEffort>? TargetEfforts { get; set; }
    public List<ExCompanyHistory>? ExCompanyHistories { get; set; }
    public string? EmployeeGroup { get; set; }
    public bool IsActive { get; set; } = true;
    public DateTime? ModifiedAt { get; set; }
    public int? ModifiedById { get; set; }
    public User? ModifiedBy { get; set; }
}