namespace DZDDashboard.Client.Localization;

public static class AppStrings
{
    public static readonly IReadOnlyDictionary<string, Dictionary<string, string>> Translations = new Dictionary<string, Dictionary<string, string>>
    {
        ["en"] = new()
        {
            ["nav.dashboard"]       = "Dashboard",
            ["nav.employees"]       = "Employees",
            ["nav.onboarding"]      = "Onboarding",
            ["nav.offboarding"]     = "Offboarding",
            ["nav.departments"]     = "Departments",
            ["nav.positions"]       = "Positions",
            ["nav.attendance"]      = "Attendance",
            ["nav.leaveManagement"] = "Leave Management",
            ["nav.training"]        = "Training",
            ["nav.performance"]     = "Performance",
            ["nav.company"]         = "Company",
            ["nav.settings"]        = "Settings",
            ["nav.myProfile"]       = "My Profile",

            ["appbar.notifications"] = "Notifications",
            ["appbar.markAllRead"]   = "Mark all read",
            ["appbar.noNotifications"] = "No notifications yet.",
            ["appbar.new"]           = "New",
            ["appbar.myProfile"]     = "My Profile",
            ["appbar.settings"]      = "Settings",
            ["appbar.logout"]        = "Logout",
            ["appbar.login"]         = "Login",

            ["common.save"]    = "Save",
            ["common.cancel"]  = "Cancel",
            ["common.delete"]  = "Delete",
            ["common.add"]     = "Add",
            ["common.complete"] = "Complete",
            ["common.yes"]     = "Yes",
            ["common.no"]      = "No",
            ["common.active"]  = "Active",
            ["common.inactive"] = "Inactive",

            ["onboarding.title"]       = "Onboarding Processes",
            ["onboarding.start"]       = "Start New Onboarding",
            ["onboarding.empty"]       = "No onboarding processes yet.",
            ["offboarding.title"]      = "Offboarding Processes",
            ["offboarding.start"]      = "Start New Offboarding",
            ["offboarding.empty"]      = "No offboarding processes yet.",
            ["lifecycle.employee"]     = "Employee",
            ["lifecycle.startDate"]    = "Start Date",
            ["lifecycle.progress"]     = "Progress",
            ["lifecycle.status"]       = "Status",
            ["lifecycle.inProgress"]   = "In progress",
            ["lifecycle.completed"]    = "Completed",
            ["lifecycle.cancelled"]    = "Cancelled",
        },
        ["tr"] = new()
        {
            ["nav.dashboard"]       = "Panel",
            ["nav.employees"]       = "Çalışanlar",
            ["nav.onboarding"]      = "İşe Alım",
            ["nav.offboarding"]     = "İşten Çıkış",
            ["nav.departments"]     = "Departmanlar",
            ["nav.positions"]       = "Pozisyonlar",
            ["nav.attendance"]      = "Devam",
            ["nav.leaveManagement"] = "İzin Yönetimi",
            ["nav.training"]        = "Eğitim",
            ["nav.performance"]     = "Performans",
            ["nav.company"]         = "Şirket",
            ["nav.settings"]        = "Ayarlar",
            ["nav.myProfile"]       = "Profilim",

            ["appbar.notifications"] = "Bildirimler",
            ["appbar.markAllRead"]   = "Tümünü okundu işaretle",
            ["appbar.noNotifications"] = "Henüz bildirim yok.",
            ["appbar.new"]           = "Yeni",
            ["appbar.myProfile"]     = "Profilim",
            ["appbar.settings"]      = "Ayarlar",
            ["appbar.logout"]        = "Çıkış Yap",
            ["appbar.login"]         = "Giriş Yap",

            ["common.save"]    = "Kaydet",
            ["common.cancel"]  = "Vazgeç",
            ["common.delete"]  = "Sil",
            ["common.add"]     = "Ekle",
            ["common.complete"] = "Tamamla",
            ["common.yes"]     = "Evet",
            ["common.no"]      = "Hayır",
            ["common.active"]  = "Aktif",
            ["common.inactive"] = "Pasif",

            ["onboarding.title"]       = "İşe Alım Süreçleri",
            ["onboarding.start"]       = "Yeni İşe Alım Başlat",
            ["onboarding.empty"]       = "Henüz işe alım süreci yok.",
            ["offboarding.title"]      = "İşten Çıkış Süreçleri",
            ["offboarding.start"]      = "Yeni İşten Çıkış Başlat",
            ["offboarding.empty"]      = "Henüz işten çıkış süreci yok.",
            ["lifecycle.employee"]     = "Çalışan",
            ["lifecycle.startDate"]    = "Başlangıç",
            ["lifecycle.progress"]     = "İlerleme",
            ["lifecycle.status"]       = "Durum",
            ["lifecycle.inProgress"]   = "Devam ediyor",
            ["lifecycle.completed"]    = "Tamamlandı",
            ["lifecycle.cancelled"]    = "İptal",
        },
    };
}
