// Icon name mapping: Old Material names -> New Lucide names
const iconMapping = {
    // Material.Filled mappings
    'Material.Filled.AccountTree': 'Workflow',
    'Material.Filled.Add': 'Plus',
    'Material.Filled.Apartment': 'Building',
    'Material.Filled.ArrowBack': 'ArrowLeft',
    'Material.Filled.Business': 'BriefcaseBusiness',
    'Material.Filled.BusinessCenter': 'Briefcase',
    'Material.Filled.CalendarMonth': 'CalendarDays',
    'Material.Filled.CloudUpload': 'CloudUpload',
    'Material.Filled.Dashboard': 'LayoutDashboard',
    'Material.Filled.Delete': 'Trash2',
    'Material.Filled.Description': 'FileText',
    'Material.Filled.Domain': 'Building2',
    'Material.Filled.Edit': 'Pencil',
    'Material.Filled.Email': 'Mail',
    'Material.Filled.Event': 'Calendar',
    'Material.Filled.EventAvailable': 'CalendarCheck',
    'Material.Filled.EventBusy': 'CalendarX',
    'Material.Filled.ExpandLess': 'ChevronUp',
    'Material.Filled.ExpandMore': 'ChevronDown',
    'Material.Filled.Groups': 'Users',
    'Material.Filled.KeyboardArrowDown': 'ChevronDown',
    'Material.Filled.KeyboardArrowUp': 'ChevronUp',
    'Material.Filled.Link': 'Link',
    'Material.Filled.LocationOn': 'MapPin',
    'Material.Filled.Logout': 'LogOut',
    'Material.Filled.Menu': 'Menu',
    'Material.Filled.NotificationsNone': 'Bell',
    'Material.Filled.People': 'Users',
    'Material.Filled.PeopleAlt': 'UsersRound',
    'Material.Filled.PeopleOutline': 'Users',
    'Material.Filled.Person': 'User',
    'Material.Filled.PersonOutline': 'UserRound',
    'Material.Filled.Phone': 'Phone',
    'Material.Filled.Schedule': 'Clock3',
    'Material.Filled.Schema': 'Network',
    'Material.Filled.School': 'GraduationCap',
    'Material.Filled.Search': 'Search',
    'Material.Filled.Settings': 'Settings',
    'Material.Filled.Shield': 'Shield',
    'Material.Filled.Timeline': 'ChartLine',
    'Material.Filled.TrendingUp': 'TrendingUp',
    'Material.Filled.Tune': 'SlidersHorizontal',
    'Material.Filled.WorkHistory': 'History',
    
    // Material.Outlined mappings
    'Material.Outlined.Accessible': 'Accessibility',
    'Material.Outlined.AlternateEmail': 'AtSign',
    'Material.Outlined.Approval': 'BadgeCheck',
    'Material.Outlined.Badge': 'IdCard',
    'Material.Outlined.Cake': 'Cake',
    'Material.Outlined.CalendarToday': 'CalendarDays',
    'Material.Outlined.ChildCare': 'Baby',
    'Material.Outlined.ContentCopy': 'Copy',
    'Material.Outlined.Description': 'FileText',
    'Material.Outlined.Edit': 'Pencil',
    'Material.Outlined.Email': 'Mail',
    'Material.Outlined.EmojiEvents': 'Trophy',
    'Material.Outlined.Event': 'Calendar',
    'Material.Outlined.FamilyRestroom': 'House',
    'Material.Outlined.Favorite': 'Heart',
    'Material.Outlined.Flag': 'Flag',
    'Material.Outlined.Home': 'House',
    'Material.Outlined.LocationCity': 'Building',
    'Material.Outlined.LocationOn': 'MapPin',
    'Material.Outlined.Person': 'User',
    'Material.Outlined.Phone': 'Phone',
    'Material.Outlined.PhoneAndroid': 'Smartphone',
    'Material.Outlined.Place': 'MapPin',
    'Material.Outlined.Public': 'Globe',
    'Material.Outlined.School': 'GraduationCap',
    'Material.Outlined.Timer': 'Timer',
    'Material.Outlined.WorkHistory': 'History',
};

export default iconMapping;
